import type { ReactNode } from 'react';

interface AlertCardProps {
  type: string;
  severity: 'info' | 'warning' | 'critical';
  description: string;
  patient: string;
  date: string;
  status: string;
  autoGenerated: boolean;
  onAcknowledge?: () => void;
  onResolve?: () => void;
}

const severityStyles = {
  critical: { border: 'border-l-red-500', text: 'text-red-500', bg: 'bg-red-50 dark:bg-red-900/20' },
  warning: { border: 'border-l-amber-500', text: 'text-amber-500', bg: 'bg-amber-50 dark:bg-amber-900/20' },
  info: { border: 'border-l-blue-500', text: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-900/20' },
};

const typeLabels: Record<string, string> = {
  pre_eclampsia: 'Pre-eclampsie',
  gestational_diabetes: 'Diabete gestationnel',
  iugr: 'RCIU',
  preterm_labor: 'Travail premature',
  anomaly: 'Anomalie',
  postpartum_depression: 'Depression post-partum',
};

export function AlertCard({
  type,
  severity,
  description,
  patient,
  date,
  status,
  autoGenerated,
  onAcknowledge,
  onResolve,
}: AlertCardProps): ReactNode {
  const style = severityStyles[severity];

  return (
    <div className={`card p-4 border-l-4 ${style.border}`}>
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-xs font-bold uppercase ${style.text}`}>
              {typeLabels[type] || type}
            </span>
            <span className="text-xs text-[var(--color-text-tertiary)]">
              {patient}
            </span>
            {autoGenerated && (
              <span className="text-xs bg-[var(--color-bg-tertiary)] text-[var(--color-text-tertiary)] px-2 py-0.5 rounded">
                Auto
              </span>
            )}
          </div>
          <p className="text-sm text-[var(--color-text-primary)]">{description}</p>
          <p className="text-xs text-[var(--color-text-tertiary)] mt-1">{date}</p>
        </div>
        {status === 'active' && (
          <div className="flex gap-2 ml-4 flex-shrink-0">
            {onAcknowledge && (
              <button onClick={onAcknowledge} className="btn-secondary text-xs px-3 py-1.5">
                Acquitter
              </button>
            )}
            {onResolve && (
              <button onClick={onResolve} className="btn-primary text-xs px-3 py-1.5">
                Resoudre
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
